require('engine.common')
Platform = require('objects.platform')
Litterbox = require('objects.litterbox')
MilkAndCookies = require('objects.milkandcookies')
HouseBrick = require('objects.housebrick')
Vine = require('objects.vine')
